### ISSUE TITLE
Is there a easy or visual method to generate this plist file?

### ISSUE THREAD

**Issue by isaced** [coolbeet/CBStoreHouseRefreshControl#1]
In this way, we needn't write it one point by one point.

**Comment by zinwalin** [comment]
cool trick.

**Comment by code1303009** [comment]
How to use UIBezierPath with 2 control point to draw it? For example,like this '[textPath addCurveToPoint: CGPointMake(480.1, 147.7) controlPoint1: CGPointMake(461, 141) controlPoint2: CGPointMake(470, 145)]'

**Comment by ghost** [comment]
nice

**Comment by 2333333333** [comment]
Maybe you can expose his color properties to the outside

**Comment by saxiang** [comment]
How to use UIBezierPath with 2 control point to draw it? For example,like this '[textPath addCurveToPoint: CGPointMake(480.1, 147.7) controlPoint1: CGPointMake(461, 141) controlPoint2: CGPointMake(470, 145)]'

**Comment by axclogo** [comment]
much too better，My brother！厉害了我的哥

**Comment by CHUANTU** [comment]
nice
