### ISSUE TITLE
ScrollView's Content Offset Changed after Refreshing

### ISSUE THREAD

**Issue by Jayvd** [coolbeet/CBStoreHouseRefreshControl#15]
Trying to use this control in my Swift project

> self.refreshControl = CBStoreHouseRefreshControl.attachToScrollView(tableView, target: self, refreshAction: "refreshTriggered:", plist: "storehouse", color: UIColor.whiteColor(), lineWidth: 1, dropHeight: 80, scale: 1, horizontalRandomness: 150, reverseLoadingAnimation: false, internalAnimationFactor: 0.5);

scrollView.contentOffset.y value was initially 0;

After refreshing, the contentOffset.y value became 80 (value of the **dropHeight** parameter)

**Comment by Jayvd** [comment]
Ahh, this was mentioned before. Sorry, closing issue

**Comment by manhcuong27** [comment]
How do I resolve this issue :( ?
