### ISSUE TITLE
iOS 8 Offsets not resetting

### ISSUE THREAD

**Issue by Natelegreat1** [coolbeet/CBStoreHouseRefreshControl#22]
After the animation is complete, the scrollView (in my case UITableView specifically) is remaining offset by about the height of the storeHouse image...
Anyone else having this issue?
Followed demo to the letter.
This is probably the coolest iOS accessory I've seen in ages and would be upset if I couldn't make use of it!!!

**Comment by Natelegreat1** [comment]
NOTE: This only occurs if you do not use a UITableViewController! -- I had a UIViewController with a UITableView in it... oh well.

**Comment by crewshin** [comment]
Same thing happens for me with a UITableViewController.

**Comment by ijpe** [comment]
Add
yourScrollView.setContentOffset(CGPoint(x: 0, y: 0), animated: false)
after
self.storeHouseRefreshControl.finishingLoading()

> Example:

``` swift
func refreshTriggered()
{
    //call your loading method here

    //Finshed loading the data, reset the refresh control
    self.storeHouseRefreshControl.finishingLoading()
    yourScrollView.setContentOffset(CGPoint(x: 0, y: 0), animated: false)
}
```
