### ISSUE TITLE
Way to change the color? 

### ISSUE THREAD

**Issue by klmitchell2** [coolbeet/CBStoreHouseRefreshControl#26]
Im trying to change the color: 

self.storeHouseRefreshControl = [CBStoreHouseRefreshControl attachToScrollView:self.tableView target:self refreshAction:@selector(refreshTriggered:) plist:@"storehouse" color:[UIColor blackColor] lineWidth:1.5 dropHeight:80 scale:1 horizontalRandomness:150 reverseLoadingAnimation:YES internalAnimationFactor:0.5];

When I change the color nothing happens. Is this possible?

**Comment by klmitchell2** [comment]
I was able to fix this by changing the color on line 114 of CBSStoreHouseRefreshControl

**Comment by Natelegreat1** [comment]
+ (CBStoreHouseRefreshControl*)attachToScrollView:(UIScrollView *)scrollView
                                           target:(id)target
                                    refreshAction:(SEL)refreshAction
                                            plist:(NSString *)plist
                                            color:(UIColor*)color
                                        lineWidth:(CGFloat)lineWidth
                                       dropHeight:(CGFloat)dropHeight
                                            scale:(CGFloat)scale
                             horizontalRandomness:(CGFloat)horizontalRandomness
                          reverseLoadingAnimation:(BOOL)reverseLoadingAnimation
                          internalAnimationFactor:(CGFloat)internalAnimationFactor


        BarItem *barItem = [[BarItem alloc] initWithFrame:refreshControl.frame startPoint:startPoint endPoint:endPoint color:[UIColor whiteColor] lineWidth:lineWidth];


[UIColor whiteColor] needs to be replaced with color -- any chance this can be done, @coolbeet ?

Thanks!!!
