### ISSUE TITLE
Suggestion : for swift version

### ISSUE THREAD

**Issue by ram2386** [coolbeet/CBStoreHouseRefreshControl#37]
The loading view is interactive and good. Please provide the swift version so that it is compatible for it.

**Comment by ijpe** [comment]
What do you need for swift?

**Comment by haithngnbak** [comment]
I think it should be able in Carthage

**Comment by peiweichen** [comment]
checkout https://github.com/peiweichen/SurfingRefreshControl @ram2386

**Comment by ram2386** [comment]
Thanks @peiweichen.
